# Generated by Django 4.1.4 on 2023-03-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_list.todolist'),
        ),
    ]
